create table rt_org(
    id varchar(255),
    has_primary_instrument text, 
    has_registered_phone_number text, 
    has_primary_economic_sector text, 
    has_registered_fax_number text, 
    headquarters_address text, 
    has_primary_industry_group text, 
    organization_name text,
    has_organization_primary_quote text, 
    is_incorporated_in text, 
    has_latest_organization_founded_date text, 
    has_primary_business_sector text, 
    has_l_e_i text, 
    has_holding_classification text, 
    registered_address text, 
    has_activity_status text, 
    has_headquarters_phone_number text, 
    has_headquarters_fax_number text, 
    has_perm_id text, 
    is_domiciled_in text, 
    has_inactive_date text, 
    has_u_r_l text, 
    has_i_p_o_date text, 
    "TYPE" text
);
