drop table organization;

create table organization(
    id varchar(255) primary key,
    "TYPE" text,
    HEADQUARTERS_ADDRESS text,
    HAS_PERM_ID text,
    HAS_ACTIVITY_STATUS text,IS_INCORPORATED_IN text,IS_DOMICILED_IN text,ORGANIZATION_NAME text,
    HAS_HEADQUARTERS_PHONE_NUMBER text,HAS_INACTIVE_DATE text,HAS_LATEST_ORGANIZATION_FOUNDED_DATE text,
    REGISTERED_ADDRESS text,HAS_HEADQUARTERS_FAX_NUMBER text,HAS_PRIMARY_BUSINESS_SECTOR text,
    HAS_PRIMARY_ECONOMIC_SECTOR text,HAS_PRIMARY_INDUSTRY_GROUP text,HAS_U_R_L text,
    HAS_I_P_O_DATE text,HAS_REGISTERED_FAX_NUMBER text,HAS_REGISTERED_PHONE_NUMBER text,
    HAS_L_E_I text,HAS_PRIMARY_INSTRUMENT text,HAS_ORGANIZATION_PRIMARY_QUOTE text,
    HAS_HOLDING_CLASSIFICATION text);
