drop table person;
create table person(
    id varchar(255) primary key,
    "TYPE" varchar(55),
    HAS_PERM_ID varchar(66),
    PREF_LABEL varchar(84),
    "RANK" varchar(2),
    "FROM" varchar(20),
    HAS_PUBLICATION_STATUS varchar(61),
    "TO" varchar(20),
    HAS_HOLDER varchar(32),
    HAS_POSITION_TYPE varchar(31),
    HAS_REPORTED_TITLE varchar(200),
    IS_POSITION_IN varchar(32),
    IS_TENURE_IN varchar(32),
    FROM_INSTITUTION_NAME varchar(208),
    WITH_DEGREE varchar(29),
    IN_SUBJECT varchar(75),
    HAS_QUALIFICATION varchar(105),
    ADDITIONAL_NAME varchar(35),
    FAMILY_NAME varchar(60),
    GIVEN_NAME varchar(59),
    HAS_TENURE_IN_ORGANIZATION varchar(32),
    HOLDS_POSITION varchar(85),
    HAS_GENDER varchar(38),
    HONORIFIC_PREFIX varchar(20),
    HONORIFIC_SUFFIX varchar(57),
    PREFERRED_NAME varchar(20),
    DATE_OF_DEATH varchar(10),
    HAS_YEAR_OF_BIRTH varchar(4));
