#!/bin/bash -v

gradle clean bootJar

rm -f jfr/*
rm -f logs/*
rm -f tmp/*

java \
 -DjdbcUrl="jdbc:postgresql://127.0.0.1:5432/$DEMO_DB" \
 -Dusername="$DEMO_USER" \
 -Dpassword="$DEMO_PWD" \
 -DhttpUrl=http://sql.ru \
 -jar build/libs/html-parser-*.jar
