#!/bin/bash -v

gradle clean bootJar

rm -f jfr/*
rm -f logs/*
rm -f tmp/*

java \
 -DjdbcUrl="$PG_DEF_JDBC_URL" \
 -Dusername="$PG_DEF_JDBC_USER" \
 -Dpassword="$PG_DEF_JDBC_PWD" \
 -DhttpUrl=http://sql.ru \
 -jar build/libs/html-parser-0.0.1-SNAPSHOT.jar
