spring :
  application :
    name: HtmlParser

walker :
  randomwalker :
    rateLimiterParameter : 0.5
  rangewalker :
    rateLimiterParameter : 0.5
  vipwalker :
    rateLimiterParameter : 0.5
    vips:
      - 4897
      - 28572
      - 27971
      - 43489
      - 111626
      - 142913
      - 251867
      - 57183
      - 95030
      - 110363
      - 263304
      - 97422
      - 21430
      - 88727
      - 252521
      - 223550
      - 257822
      - 132113
      - 19857
      - 11587
      - 22920
      - 122827
      - 57183
      - 101262
      - 247232
      - 261581
      - 49068
      - 145849
      - 24806
      - 4045
      - 30055
      - 4313
      - 1
      - 7389
      - 9662
      - 27590
      - 146456
      - 4045
      - 43053
      - 85869
      - 95721

hikariconfig :
  driverClassName : "org.postgresql.Driver"
  jdbcUrl : "jdbc:postgresql://127.0.0.1:5432/*****"
  username : ***
  password : ***

