@startuml

class Stack {
    StackId : arn
    --
    StackName
    TemplateDesc
    LastUpdateTime: datetime
    StackStatus : StatusEnum
    DriftInfo : DriftInfoType
}

class DriftInfoType {

}

enum StatusEnum {
    CREATE_COMPLETE
}

@enduml


