#!/bin/bash -v

mvn clean package

export LIMIT=$1
export SELECTION=$2

java -jar target/probe-compression-1.0-SNAPSHOT.jar "$LIMIT" "$SELECTION"

gzip -f -k     "graphs/war-and-society-1-2-3-4-graph.bin"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-graph.bin"

gzip -f -k     "trie/war-and-society-1-2-3-4.dict.trie"
bzip2 -z -k -f "trie/war-and-society-1-2-3-4.dict.trie"

gzip -f -k     "graphs/war-and-society-1-2-3-4-graph-normalized.csv"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-graph-normalized.csv"

gzip -f -k     "graphs/war-and-society-1-2-3-4-graph-normalized.csv"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-graph-normalized.csv"

gzip -f -k     "graphs/war-and-society-1-2-3-4-graph-vlq.bin"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-graph-vlq.bin"

gzip -f -k     "graphs/war-and-society-1-2-3-4-adjacency-list.csv"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-adjacency-list.csv"

gzip -f -k     "graphs/war-and-society-1-2-3-4-adjacency-list.bin"
bzip2 -z -k -f "graphs/war-and-society-1-2-3-4-adjacency-list.bin"


exit
rm -f "$format.log"

#for format in neato twopi circo dot ;
for format in dot ;
do  
  echo "Rendering into PNG $format" | tee -a "$format.log"
  dot graphviz/war-and-society-1-2-3-4.dot -v -s[96] -Tpng "-K$format" "-oimages/war-and-society-1-2-3-4-limit-$LIMIT-$format.png" 2>&1 | tee -a "$format.log"
  echo "Done with errorcode=$?" | tee -a "$format.log"

  echo "Rendering into SVG $format" | tee -a "$format.log"
  dot graphviz/war-and-society-1-2-3-4.dot -v -s[96] -Tsvg "-K$format" "-oimages/war-and-society-1-2-3-4-limit-$LIMIT-$format.svg" 2>&1 | tee -a "$format.log"
  echo "Done with errorcode=$?" | tee -a "$format.log"
  
  gzip -f -k -9 "images/war-and-society-1-2-3-4-limit-$LIMIT-$format.svg"
done;

