
<ruleset> ::= ((<comment> | <rule>) "\n"+)*
<comment> ::= "#" {<any character>}
<rule> ::= <pattern> <whitespace> "->" <whitespace> ["."] <replacement>
<whitespace> ::= ("\t" | " ") [<whitespace>]
