[package]
name = "islands-rust"
version = "0.1.0"
authors = ["mayton"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
png = "0.15.3"
rand = "0.7.3"

