#!/bin/bash -v

gcc \
  -g \
  -Wall  \
  -shared \
  -o librnb-tree.so \
  rnb-tree.c

echo "[1.1] Status : $?"

#Arcive:
#ar rsc librnb-tree.a rnb-tree.so

readelf -s librnb-tree.so > librnb-tree-symbols.txt

echo "[1.2] Status : $?"

objdump -t librnb-tree.so > librnb-tree-objdump.txt

echo "[1.3] Status : $?"

ldd -v librnb-tree.so > librnb-tree-ldd.txt

echo "[1.4] Status : $?"

nm -D librnb-tree.so > librnb-tree-nm.txt

echo "[1.5] Status : $?"

rm benchmark.exe

gcc \
  -g \
  -Wall \
  benchmark.c \
  -Llibs \
  -L. \
  -ldl \
  -o benchmark.exe

#  -l:librnb-tree.so \

echo "[3] Status : $?"

./benchmark.exe

# readelf -a rnb-tree.so | less
# nm -D      rnb-tree.so | less
# ldd        rnb-tree.so | less

#  For example, a program 'data.c' using the GNU Linear Programming library 'libglpk.a', which in turn uses the math library 'libm.a', should be compiled as,
# $ gcc -Wall data.c -lglpk -lm

# $ ar rcs libmylib.a file2.o

# $ gcc file1.c -Llibs -lmylib -o outfile
# gcc -o driver driver.o -L. -l_mylib
